; -= Jezebel Configuration File =-
; Thank you for trying out this wonderful game that I put many many
; hours into. This game is still new, and may have bugs, so please
; let me know if you find any. Check for new versions at:
; HTTP://www.kinn.com/brian
; or Email me at:
; ZEUS@EXEC.TSCNET.COM    Thanks.
; -= Jezebel Configuration File =-
BBSNAME Happy
SYSOPFIRST Happy
SYSOPLAST Gilmore
BBSType DOORSYS
LOCKBAUD 38400
XFOSSIL
